<?php

//
// Hooks
//

/**
* Implementation of hook_menu().
*/
function vivaldi_orders_menu() {
  
  $items['preorders/fulfillment'] = array(
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'page callback' => 'vivaldi_orders_fulfillment_page',
    'title' => 'Pre-Order Fulfillment'
    );
  
  $items['preorders/success'] = array(
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'page callback' => 'vivaldi_orders_success_page',
    );
  
  return $items;
}

//
// Page handlers
//

/**
* Order fulfillment page
*/
function vivaldi_orders_fulfillment_page() {
  return drupal_get_form('vivaldi_orders_fulfillment_form');
}

/**
* tmp page
*/
function vivaldi_orders_success_page() {
  return 'Got it';
}

//
// Form API Functions
//
/**
* Order fulfillment form
*/
function vivaldi_orders_fulfillment_form() {
    $form = array();
 
    $form['Name']=array(
        '#type'=>'textfield',
        '#required'=>true,
        '#default_value'=>' ',
        '#title'=>t('Full Name'),
        '#size'=>50,
        '#maxlength'=>128,
        '#weight'=>1);
 
    $form['Email']=array(
        '#type'=>'textfield',
        '#required'=>true,
        '#default_value'=>' ',
        '#title'=>t('Email Address'),
        '#size'=>50,
        '#maxlength'=>128,
        '#weight'=>2);
    
    $form['Reg_code']=array(
        '#type'=>'textfield',
        '#required'=>true,
        '#default_value'=>' ',
        '#title'=>t('Registration Code'),
        '#size'=>50,
        '#maxlength'=>128,
        '#weight'=>3);
    
    $form['submit']=array(
        '#type'=>'submit',
        '#value'=>'submit',
        '#weight'=>4);
 
      return $form;
}

function vivaldi_orders_fulfillment_form_validate($form, &$form_state) {
  // look for this reg code
  $query = "SELECT * from {vivaldi_orders} WHERE Reg_code = '%s' AND Active = '1'";
  $order_lookup = db_query($query, $form_state['values']['Reg_code']);
  
  if ($order = db_fetch_array($order_lookup)) {
    // Save order for submit function
    $form_state['vivaldi_orders']['order'] = $order;
    
    //reg code found, check that the email address matches
    if (strtolower($form_state['values']['Email']) != strtolower($order['Email'])) {
      form_set_error('Email', t('This email address does not match the registration code.'));
      return;
    }
    
  } else {
    //reg code not found
    form_set_error('Reg_code', t('This registration code was not found or has already been used.'));
    return;
  }
}

function vivaldi_orders_fulfillment_form_submit($form, &$form_state) {
  // Don't allow user to add to cart multiple times
  uc_cart_empty(uc_cart_get_id());

  //Get the quantity for the pre-order
  $qty = empty($form_state['vivaldi_orders']['order']['Quantity']) ? 1 : $form_state['vivaldi_orders']['order']['Quantity'];
  
  // Validation OK, add the item
  uc_cart_add_item(3, $qty);
  
  $form_state['redirect'] = 'cart';
}


  