<?php

//
// Hooks
//

/**
* Implementation of hook_menu().
*/
function vivaldi_orders_menu() {
  
  $items['preorders/fulfillment'] = array(
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'page callback' => 'vivaldi_orders_fulfillment_page',
    'title' => 'Pre-Order Fulfillment'
    );
  
  $items['preorders/success'] = array(
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'page callback' => 'vivaldi_orders_success_page',
    );
  
  return $items;
}

//
// Page handlers
//

/**
* Order fulfillment page
*/
function vivaldi_orders_fulfillment_page() {
  return drupal_get_form('vivaldi_orders_fulfillment_form');
}

/**
* tmp page
*/
function vivaldi_orders_success_page() {
  return 'Got it';
}

//
// Form API Functions
//
/**
* Order fulfillment form
*/
function vivaldi_orders_fulfillment_form() {
    $form = array();
    $form['#redirect'] = 'preorders/success';
 
    $form['Name']=array(
        '#type'=>'textfield',
        '#required'=>true,
        '#default_value'=>' ',
        '#title'=>t('Enter Full Name'),
        '#size'=>50,
        '#maxlength'=>128,
        '#weight'=>1);
 
    $form['Email']=array(
        '#type'=>'textfield',
        '#required'=>true,
        '#default_value'=>' ',
        '#title'=>t('Enter Email Address'),
        '#size'=>50,
        '#maxlength'=>128,
        '#weight'=>1);
    
    $form['Reg_code']=array(
        '#type'=>'textfield',
        '#required'=>true,
        '#default_value'=>' ',
        '#title'=>t('Enter Registration Code'),
        '#size'=>50,
        '#maxlength'=>128,
        '#weight'=>1);
    
    $form['submit']=array(
        '#type'=>'submit',
        '#value'=>'submit',
        '#weight'=>2);
 
      return $form;
}

function vivaldi_orders_fulfillment_form_validate($form, &$form_state) {
  // look for this reg code
  $order_lookup = db_query("SELECT * from {vivaldi_orders} WHERE Reg_code = '%s'", $form_state['values']['Reg_code']);
  
  if ($order = db_fetch_array($order_lookup)) {
    //reg code found, check that the email address matches
    if (strtolower($form_state['values']['Email']) != strtolower($order['Email'])) {
      form_set_error('Email', t('This email address does not match the registration code.'));
      return;
    }
  } else {
    //reg code not found
    form_set_error('Reg_code', t('This registration code was not found.'));
    return;
  }
  
  //form_set_error('Name', t('form invalid.'));
}

function vivaldi_orders_fulfillment_form_submit($form, &$form_state) {
  //db_query("INSERT INTO {table} (name, log, hidden) VALUES ('%s', %d, '%s')", $form_state['values']['name'], $form_state['values']['access']['log'],  $form_state['values']['hidden']);
  drupal_set_message(t('Your form has been saved.'));
}


  